<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE vivero [
<!ELEMENT vivero(especie+)>
<!ELEMENT especie(nombre,precio,variedad,origen,color_fruto+,otros_datos)>
<!ATTLIST especie siembra CDATA (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT variedad (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT color_fruto (#PCDATA)>
<!ELEMENT otros_datos(maduracion,riego)>
<!ELEMENT maduracion (#PCDATA)>
<!ELEMENT riego (#PCDATA)>

<!ATTLIST precio moneda CDATA IMPLIED>
]>


<vivero>
    <especie siembra="2018">
        <nombre>Litchi</nombre>
        <precio moneda="euro">25</precio>
        <variedad>Kway May Pink</variedad>
        <origen>Filipinas</origen>
        <color_fruto>rojo</color_fruto>
        <color_fruto>rosa</color_fruto>
        <otros_datos>
            <maduracion>agosto</maduracion>
            <riego>diario</riesgo>
        </otros_datos>
    </especie>
    <especie siembra="2017">
        <nombre>Longan</nombre>
        <precio moneda="euro"> 10 </precio>
        <variedad>Champoo </variedad>
        <origen>China</origen>
        <color_fruto>marr√≥n</color_fruto>
        <otros_datos>
            <maduracion>octubre</maduracion>
            <riego>diario</riego>
        </otros_datos>
    </especie>
    <especie siembra="2016">
        <nombre>Litchi</nombre>
        <precio moneda="euro"> 21 </precio>
        <variedad>mauritius </variedad>
        <origen>Florida</origen>
        <color_fruto>rojo</color_fruto>
        <otros_datos>
            <maduracion>agosto</maduracion>
            <riego>diario</riego>
        </otros_datos>
    </especie>
</vivero>